/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.cadastrarnf;

import controller.ProdutoController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.ItemNFCompra;
import model.Produto;

/**
 *
 * @author joaop
 */
public class NFVendaProdutoConsultar extends javax.swing.JFrame {

    private List<ItemNFCompra> itensNFCompras;
    private NFCadastrarVisao nfCadastrarVisao;

    public NFVendaProdutoConsultar() {
        initComponents();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i = 0; i < tabelaConsultaNFvenda.getColumnCount(); i++) {
            tabelaConsultaNFvenda.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        setTitle("Lanchonete Ota's - Consultar Produto");
        setLocationRelativeTo(null);
        spinQuantidade.setValue(1);
    }

    public NFVendaProdutoConsultar(NFCadastrarVisao nfCadastrarVisao) {
        initComponents();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i = 0; i < tabelaConsultaNFvenda.getColumnCount(); i++) {
            tabelaConsultaNFvenda.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        setTitle("Lanchonete Ota's - Consulta de Produto");
        setLocationRelativeTo(null);
        this.nfCadastrarVisao = nfCadastrarVisao;
        spinQuantidade.setValue(1);
    }

    public NFVendaProdutoConsultar(NFCadastrarVisao nfCadastrarVisao, List<ItemNFCompra> itensNFCompras) {
        initComponents();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i = 0; i < tabelaConsultaNFvenda.getColumnCount(); i++) {
            tabelaConsultaNFvenda.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        setTitle("Lanchonete Ota's - Consulta de Produto");
        setLocationRelativeTo(null);
        this.itensNFCompras = itensNFCompras;
        this.nfCadastrarVisao = nfCadastrarVisao;
        spinQuantidade.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsultaNFvenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinQuantidade = new javax.swing.JSpinner();
        txtProdutoCodigo = new javax.swing.JTextField();
        txtProdutoNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaConsultaNFvenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Valor", "Estoque", "Imposto", "Unidade"
            }
        ));
        tabelaConsultaNFvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaNFvendaMouseClicked(evt);
            }
        });
        tabelaConsultaNFvenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaConsultaNFvendaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaConsultaNFvenda);

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Quantidade:");

        spinQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinQuantidadeStateChanged(evt);
            }
        });

        txtProdutoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoCodigoActionPerformed(evt);
            }
        });

        txtProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoNomeActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spinQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoNomeActionPerformed

    private void txtProdutoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoCodigoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtProdutoNome.getText().length() == 0 && txtProdutoCodigo.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Você precisa inserir um código ou um nome do produto.");
                return;
            }
            if (txtProdutoCodigo.getText().length() > 0) {
                ProdutoController produtoController = new ProdutoController();
                List<Produto> produtos = produtoController.consultarPorCodigo(Integer.parseInt(txtProdutoCodigo.getText()));
                DefaultTableModel model = (DefaultTableModel) tabelaConsultaNFvenda.getModel();
                model.setNumRows(0);
                for (Produto produto : produtos) {
                    model.addRow(produto.getDadosModel());
                }
            } else if (txtProdutoNome.getText().length() > 0) {
                ProdutoController produtoController = new ProdutoController();
                List<Produto> produtos = produtoController.consultarPorNome(txtProdutoNome.getText());
                DefaultTableModel model = (DefaultTableModel) tabelaConsultaNFvenda.getModel();
                model.setNumRows(0);
                for (Produto produto : produtos) {
                    model.addRow(produto.getDadosModel());
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Um erro ocorreu, tente novamente.");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tabelaConsultaNFvendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaConsultaNFvendaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaConsultaNFvendaKeyPressed

    private void spinQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinQuantidadeStateChanged
        // TODO add your handling code here:
        try {
            int quantidadeVoltar = Integer.parseInt(spinQuantidade.getPreviousValue().toString());
            int quantidade = Integer.parseInt(spinQuantidade.getValue().toString());
            if (quantidadeVoltar < 1 || quantidade < 1) {
                spinQuantidade.setValue(1);
            }
        } catch (Exception e) {
            spinQuantidade.setValue(1);
            System.out.println(e);
        }
    }//GEN-LAST:event_spinQuantidadeStateChanged

    private void tabelaConsultaNFvendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaNFvendaMouseClicked
        // TODO add your handling code here:
        try {
            Integer codigo = (Integer) tabelaConsultaNFvenda.getModel().getValueAt(tabelaConsultaNFvenda.getSelectedRow(), 0);
            String nome = (String) tabelaConsultaNFvenda.getModel().getValueAt(tabelaConsultaNFvenda.getSelectedRow(), 1);
            Double valor = (Double) tabelaConsultaNFvenda.getModel().getValueAt(tabelaConsultaNFvenda.getSelectedRow(), 2);
            Integer estoque = (Integer) tabelaConsultaNFvenda.getModel().getValueAt(tabelaConsultaNFvenda.getSelectedRow(), 3);
            Double imposto = (Double) tabelaConsultaNFvenda.getModel().getValueAt(tabelaConsultaNFvenda.getSelectedRow(), 4);
            String unidade = (String) tabelaConsultaNFvenda.getModel().getValueAt(tabelaConsultaNFvenda.getSelectedRow(), 5);
            Integer quantidade = (Integer) spinQuantidade.getValue();
            Produto produto = new Produto();
            produto.setCodigo(codigo);
            produto.setNome(nome);
            produto.setValor(valor);
            produto.setEstoque(estoque);
            produto.setImposto(imposto);
            produto.setUnidade(unidade);
            ItemNFCompra itemNFCompra = new ItemNFCompra();
            itemNFCompra.setCodigo(1);
            itemNFCompra.setCodigo_nf(0);
            itemNFCompra.setCodigo_produto(produto.getCodigo());
            itemNFCompra.setQuantidade(quantidade);
            itemNFCompra.setValor_uni(produto.getValor());
            itemNFCompra.setValor_total(produto.getValor() * itemNFCompra.getQuantidade());
            itemNFCompra.setProduto(produto);
            itensNFCompras.add(itemNFCompra);
            this.nfCadastrarVisao.setItensNFCompra(itensNFCompras);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tabelaConsultaNFvendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NFVendaProdutoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NFVendaProdutoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NFVendaProdutoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NFVendaProdutoConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NFVendaProdutoConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinQuantidade;
    private javax.swing.JTable tabelaConsultaNFvenda;
    private javax.swing.JTextField txtProdutoCodigo;
    private javax.swing.JTextField txtProdutoNome;
    // End of variables declaration//GEN-END:variables
}
