/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.consultarnf;

import controller.NFCompraController;
import controller.NFVendaController;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.NFCompra;
import model.NFVenda;
import visao.usuario.TelaMenu;

/*
 * @author joaop
 */
public class NFConsultarVisao extends javax.swing.JFrame {

    /**
     * Creates new form NFConsultarVisao
     */
    public NFConsultarVisao() {
        initComponents();

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        for (int i = 0; i < tableConsulta.getColumnCount(); i++) {
            tableConsulta.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        setTitle("Lanchonete Ota's - Consultar NF");
        setLocationRelativeTo(null);

        try {
            MaskFormatter mask = new MaskFormatter("##/##/####");
            mask.setPlaceholderCharacter('_');
            txtDataApartir.setFormatterFactory(new DefaultFormatterFactory(mask));
            txtDataAte.setFormatterFactory(null);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupNF = new javax.swing.ButtonGroup();
        titleConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDataApartir = new javax.swing.JFormattedTextField();
        txtDataAte = new javax.swing.JFormattedTextField();
        radioNFCompra = new javax.swing.JRadioButton();
        radioNFVenda = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleConsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleConsulta.setText("Lanchonete Ota's- Consultar NF");
        titleConsulta.setToolTipText("");
        titleConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Data Emissão", "Valor", "CNPJ"
            }
        ));
        jScrollPane1.setViewportView(tableConsulta);

        jLabel2.setText("Apartir de: ");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel3.setText("Até:");

        txtDataApartir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDataApartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataApartirActionPerformed(evt);
            }
        });

        txtDataAte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDataAte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAteActionPerformed(evt);
            }
        });

        groupNF.add(radioNFCompra);
        radioNFCompra.setText("NF Compra");
        radioNFCompra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioNFCompraItemStateChanged(evt);
            }
        });

        groupNF.add(radioNFVenda);
        radioNFVenda.setText("NF Venda");
        radioNFVenda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioNFVendaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataApartir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioNFVenda)
                        .addGap(18, 18, 18)
                        .addComponent(radioNFCompra)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleConsulta)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtDataApartir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDataAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radioNFCompra)
                        .addComponent(radioNFVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnConsultar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling    String dataInicio = dateApartir.getText();
        this.setVisible(false);
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtDataApartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataApartirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataApartirActionPerformed

    private void txtDataAteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAteActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        try {

            String dataApartirString = txtDataApartir.getText().trim();
            String dataAteString = txtDataAte.getText().trim();

            Date dataApartir = null;
            Date dataAte = null;

            String regexData = "^\\d{2}/\\d{2}/\\d{4}$";
            if (!dataApartirString.isEmpty() && dataApartirString.length() == 10) {
                if (dataApartirString.matches(regexData)) {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date dataEmissaoUtil = sdf.parse(dataApartirString);
                    Date dataEmissaoSQL = new Date(dataEmissaoUtil.getTime());
                    dataApartir = dataEmissaoSQL;
                } else {
                    JOptionPane.showMessageDialog(this, "Você não inseriu uma data inicial correta.", null, JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Você não inseriu a data inicial.", null, JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!dataAteString.isEmpty() && dataAteString.length() == 10) {
                if (dataAteString.matches(regexData)) {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    java.util.Date dataEmissaoUtil = sdf.parse(dataAteString);
                    Date dataEmissaoSQL = new Date(dataEmissaoUtil.getTime());
                    dataAte = dataEmissaoSQL;
                } else {
                    dataAte = new Date(System.currentTimeMillis());
                }
            } else {
                dataAte = new Date(System.currentTimeMillis());
            }

            if (radioNFVenda.isSelected()) {
                
                tableConsulta.getColumnModel().getColumn(3).setHeaderValue("CPF");
                tableConsulta.getTableHeader().repaint();

                NFVendaController nfVendaController = new NFVendaController();
                List<NFVenda> nfVendas = nfVendaController.procurarNFVendaPorData(dataApartir, dataAte);
                DefaultTableModel model = (DefaultTableModel) tableConsulta.getModel();
                model.setNumRows(0);
                for (NFVenda nfCompra : nfVendas) {
                    model.addRow(nfCompra.getDadosModel());
                }

            } else if (radioNFCompra.isSelected()) {
                
                tableConsulta.getColumnModel().getColumn(3).setHeaderValue("CNPJ");
                tableConsulta.getTableHeader().repaint();

                NFCompraController nfCompraController = new NFCompraController();
                List<NFCompra> nfCompras = nfCompraController.procurarNFCompraPorData(dataApartir, dataAte);
                DefaultTableModel model = (DefaultTableModel) tableConsulta.getModel();
                model.setNumRows(0);
                for (NFCompra nfCompra : nfCompras) {
                    model.addRow(nfCompra.getDadosModel());
                }

            } else {
                JOptionPane.showMessageDialog(this, "Você não selecionou o tipo da nota fiscal.", null, JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Um erro ocorreu ao buscar as notas fiscais.", null, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void radioNFVendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioNFVendaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNFVendaItemStateChanged

    private void radioNFCompraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioNFCompraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNFCompraItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NFConsultarVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NFConsultarVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NFConsultarVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NFConsultarVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NFConsultarVisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup groupNF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNFCompra;
    private javax.swing.JRadioButton radioNFVenda;
    private javax.swing.JTable tableConsulta;
    private javax.swing.JLabel titleConsulta;
    private javax.swing.JFormattedTextField txtDataApartir;
    private javax.swing.JFormattedTextField txtDataAte;
    // End of variables declaration//GEN-END:variables
}
